<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2E2E919R1"><DocLocation><![CDATA[C:\OnStack_InStoreSales\Automation\TestScripts\TC_75]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[TC_75]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[2/1/2022 - 15:25:18]]></Time>
<TimeTick>1643729118</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="8" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[2/1/2022 - 15:25:18]]></Time>
<TimeTick>1643729118</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:25:28]]></Time>
<TimeTick>1643729128</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:25:28]]></Time>
<TimeTick>1643729128</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Evolution.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:25:28]]></Time>
<TimeTick>1643729128</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="47" >
<Disp><![CDATA[Evolution.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="46" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="45" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[2/1/2022 - 15:25:30]]></Time>
<TimeTick>1643729130</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Evolution.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:25:30]]></Time>
<TimeTick>1643729130</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="50" >
<Disp><![CDATA[Evolution.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="49" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[Evolution button should click]]></Obj>
<Details ><![CDATA[Evolution button doesn't exist]]></Details>
<Time><![CDATA[2/1/2022 - 15:25:30]]></Time>
<TimeTick>1643729130</TimeTick>
<NodeArgs eType="User" icon="10" nRep="51" status="Failed" >
<Disp><![CDATA[Evolution button should click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:27:03]]></Time>
<TimeTick>1643729223</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:27:03]]></Time>
<TimeTick>1643729223</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[store.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:27:03]]></Time>
<TimeTick>1643729223</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="265" >
<Disp><![CDATA[store.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="264" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="263" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[Enter the Evolution store ID]]></Obj>
<Details ><![CDATA[The Evolution store ID page is not loaded]]></Details>
<Time><![CDATA[2/1/2022 - 15:27:03]]></Time>
<TimeTick>1643729223</TimeTick>
<NodeArgs eType="User" icon="10" nRep="266" status="Failed" >
<Disp><![CDATA[Enter the Evolution store ID]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:27:36]]></Time>
<TimeTick>1643729256</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:27:36]]></Time>
<TimeTick>1643729256</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[mat-autocomplete-0.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:27:36]]></Time>
<TimeTick>1643729256</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="410" >
<Disp><![CDATA[mat-autocomplete-0.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Submit.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:28:10]]></Time>
<TimeTick>1643729290</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="552" >
<Disp><![CDATA[Submit.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[WebEdit.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:28:40]]></Time>
<TimeTick>1643729320</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="764" >
<Disp><![CDATA[WebEdit.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="409" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="408" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[Enter user name]]></Obj>
<Details ><![CDATA[User Name filed does not exist ]]></Details>
<Time><![CDATA[2/1/2022 - 15:28:40]]></Time>
<TimeTick>1643729320</TimeTick>
<NodeArgs eType="User" icon="10" nRep="765" status="Failed" >
<Disp><![CDATA[Enter user name]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:29:10]]></Time>
<TimeTick>1643729350</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:29:10]]></Time>
<TimeTick>1643729350</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[WebEdit_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:29:10]]></Time>
<TimeTick>1643729350</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="909" >
<Disp><![CDATA[WebEdit_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="908" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="907" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[Enter password]]></Obj>
<Details ><![CDATA[Password filed does not exist ]]></Details>
<Time><![CDATA[2/1/2022 - 15:29:10]]></Time>
<TimeTick>1643729350</TimeTick>
<NodeArgs eType="User" icon="10" nRep="910" status="Failed" >
<Disp><![CDATA[Enter password]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:29:41]]></Time>
<TimeTick>1643729381</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:29:41]]></Time>
<TimeTick>1643729381</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Login.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:29:41]]></Time>
<TimeTick>1643729381</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="1051" >
<Disp><![CDATA[Login.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="1050" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="1049" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:30:13]]></Time>
<TimeTick>1643729413</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:30:13]]></Time>
<TimeTick>1643729413</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Just log me in.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:30:13]]></Time>
<TimeTick>1643729413</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="1326" >
<Disp><![CDATA[Just log me in.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="1325" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="1324" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:30:43]]></Time>
<TimeTick>1643729443</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:30:43]]></Time>
<TimeTick>1643729443</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA["Click here to re-try loading"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2/1/2022 - 15:30:43]]></Time>
<TimeTick>1643729443</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="1606" status="Warning" >
<Disp><![CDATA["Click here to re-try loading"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA["Click here to re-try loading"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=Click here to re-try loading the Intranet anyway<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br>]]></Details>
<Time><![CDATA[2/1/2022 - 15:30:43]]></Time>
<TimeTick>1643729443</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="1607" >
<Disp><![CDATA["Click here to re-try loading"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Click here to re-try loading.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/1/2022 - 15:30:43]]></Time>
<TimeTick>1643729443</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="1608" >
<Disp><![CDATA[Click here to re-try loading.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="1605" status="Warning" >
<Disp><![CDATA[Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="1604" status="Warning" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[Evolution home Page should display]]></Obj>
<Details ><![CDATA[Evolution home Page has displayed successfully]]></Details>
<Time><![CDATA[2/1/2022 - 15:30:43]]></Time>
<TimeTick>1643729443</TimeTick>
<NodeArgs eType="User" icon="10" nRep="1609" status="Passed" >
<Disp><![CDATA[Evolution home Page should display]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:31:15]]></Time>
<TimeTick>1643729475</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:31:15]]></Time>
<TimeTick>1643729475</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[NC_QuickLink.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:31:15]]></Time>
<TimeTick>1643729475</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="1890" >
<Disp><![CDATA[NC_QuickLink.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="1889" >
<Disp><![CDATA[Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="1888" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj ><![CDATA[Click on QuickLinks]]></Obj>
<Details ><![CDATA[Clicked on Quick Links]]></Details>
<Time><![CDATA[2/1/2022 - 15:31:15]]></Time>
<TimeTick>1643729475</TimeTick>
<NodeArgs eType="User" icon="10" nRep="1891" status="Failed" >
<Disp><![CDATA[Click on QuickLinks]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:31:37]]></Time>
<TimeTick>1643729497</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:31:37]]></Time>
<TimeTick>1643729497</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA["Sales"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2/1/2022 - 15:31:37]]></Time>
<TimeTick>1643729497</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="1936" status="Warning" >
<Disp><![CDATA["Sales"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA["Sales"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=Sales<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br>]]></Details>
<Time><![CDATA[2/1/2022 - 15:31:37]]></Time>
<TimeTick>1643729497</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="1937" >
<Disp><![CDATA["Sales"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Sales.HoverTap]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/1/2022 - 15:31:37]]></Time>
<TimeTick>1643729497</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="1938" >
<Disp><![CDATA[Sales.HoverTap]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA["NC New Consumer Sale"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2/1/2022 - 15:32:08]]></Time>
<TimeTick>1643729528</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="2209" status="Warning" >
<Disp><![CDATA["NC New Consumer Sale"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA["NC New Consumer Sale"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=NC New Consumer Sale<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br>]]></Details>
<Time><![CDATA[2/1/2022 - 15:32:08]]></Time>
<TimeTick>1643729528</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="2210" >
<Disp><![CDATA["NC New Consumer Sale"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[NC New Consumer Sale.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/1/2022 - 15:32:08]]></Time>
<TimeTick>1643729528</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="2211" >
<Disp><![CDATA[NC New Consumer Sale.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA["NC New Consumer Sale"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[2/1/2022 - 15:32:28]]></Time>
<TimeTick>1643729548</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="2255" status="Warning" >
<Disp><![CDATA["NC New Consumer Sale"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA["NC New Consumer Sale"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=NC New Consumer Sale<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br>]]></Details>
<Time><![CDATA[2/1/2022 - 15:32:28]]></Time>
<TimeTick>1643729548</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="2256" >
<Disp><![CDATA["NC New Consumer Sale"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[NC New Consumer Sale.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/1/2022 - 15:32:28]]></Time>
<TimeTick>1643729548</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="2257" >
<Disp><![CDATA[NC New Consumer Sale.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="1935" status="Warning" >
<Disp><![CDATA[Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="1934" status="Warning" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA[Click on NC New Consumer Sale link]]></Obj>
<Details ><![CDATA[Clicked on NC New Consumer Sale link]]></Details>
<Time><![CDATA[2/1/2022 - 15:32:29]]></Time>
<TimeTick>1643729549</TimeTick>
<NodeArgs eType="User" icon="10" nRep="2258" status="Passed" >
<Disp><![CDATA[Click on NC New Consumer Sale link]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:33:31]]></Time>
<TimeTick>1643729611</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:33:31]]></Time>
<TimeTick>1643729611</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[eposTab&&0Frame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2/1/2022 - 15:33:31]]></Time>
<TimeTick>1643729611</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Scan / PLU.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:33:31]]></Time>
<TimeTick>1643729611</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="2818" >
<Disp><![CDATA[Scan / PLU.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Search..Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:34:32]]></Time>
<TimeTick>1643729672</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="3377" >
<Disp><![CDATA[Search..Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:35:33]]></Time>
<TimeTick>1643729733</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="3929" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ WebElement ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:36:34]]></Time>
<TimeTick>1643729794</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="4483" >
<Disp><![CDATA[[ WebElement ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:36:44]]></Time>
<TimeTick>1643729804</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="4561" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2/1/2022 - 15:36:44]]></Time>
<TimeTick>1643729804</TimeTick>
<NodeArgs eType="General" icon="18" nRep="4562" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="17" nRep="2817" >
<Disp><![CDATA[eposTab&&0Frame]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="2816" >
<Disp><![CDATA[Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="2815" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2/1/2022 - 15:25:15" eTime="2/1/2022 - 15:36:44" passed="4" failed="5" warnings="4" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[TC_75 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2/1/2022 - 15:25:13" eTime="2/1/2022 - 15:36:44" passed="4" failed="5" warnings="4" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test TC_75 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>