<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2E2E919R1"><DocLocation><![CDATA[C:\OnStack_InStoreSales\Automation\TestScripts\TC_75]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[TC_75]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[2/1/2022 - 15:17:52]]></Time>
<TimeTick>1643728672</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="8" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[2/1/2022 - 15:17:52]]></Time>
<TimeTick>1643728672</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:17:52]]></Time>
<TimeTick>1643728672</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:17:52]]></Time>
<TimeTick>1643728672</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Evolution.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/1/2022 - 15:17:52]]></Time>
<TimeTick>1643728672</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" >
<Disp><![CDATA[Evolution.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="12" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Evolution.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/1/2022 - 15:17:53]]></Time>
<TimeTick>1643728673</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" >
<Disp><![CDATA[Evolution.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[2/1/2022 - 15:17:53]]></Time>
<TimeTick>1643728673</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Evolution.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/1/2022 - 15:17:53]]></Time>
<TimeTick>1643728673</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="16" >
<Disp><![CDATA[Evolution.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Evolution.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[2/1/2022 - 15:17:53]]></Time>
<TimeTick>1643728673</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="18" >
<Disp><![CDATA[Evolution.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="15" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Evolution button should click]]></Obj>
<Details ><![CDATA[Evolution button clicked successfully]]></Details>
<Time><![CDATA[2/1/2022 - 15:17:53]]></Time>
<TimeTick>1643728673</TimeTick>
<NodeArgs eType="User" icon="10" nRep="19" status="Passed" >
<Disp><![CDATA[Evolution button should click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:18:15]]></Time>
<TimeTick>1643728695</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:18:15]]></Time>
<TimeTick>1643728695</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[store.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/1/2022 - 15:18:15]]></Time>
<TimeTick>1643728695</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="24" >
<Disp><![CDATA[store.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="23" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="22" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[Evolution store ID page should launch]]></Obj>
<Details ><![CDATA[Evolution store ID page has launched successfully]]></Details>
<Time><![CDATA[2/1/2022 - 15:18:15]]></Time>
<TimeTick>1643728695</TimeTick>
<NodeArgs eType="User" icon="10" nRep="25" status="Passed" >
<Disp><![CDATA[Evolution store ID page should launch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:18:17]]></Time>
<TimeTick>1643728697</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:18:17]]></Time>
<TimeTick>1643728697</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[store.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2/1/2022 - 15:18:17]]></Time>
<TimeTick>1643728697</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="29" >
<Disp><![CDATA[store.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[store.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["919"]]></Details>
<Time><![CDATA[2/1/2022 - 15:18:17]]></Time>
<TimeTick>1643728697</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="32" >
<Disp><![CDATA[store.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="28" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="27" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj ><![CDATA[Enter Evolution Store ID]]></Obj>
<Details ><![CDATA[Entered the evolution store ID and store ID 919]]></Details>
<Time><![CDATA[2/1/2022 - 15:18:17]]></Time>
<TimeTick>1643728697</TimeTick>
<NodeArgs eType="User" icon="10" nRep="33" status="Passed" >
<Disp><![CDATA[Enter Evolution Store ID]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:18:50]]></Time>
<TimeTick>1643728730</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:18:50]]></Time>
<TimeTick>1643728730</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[mat-autocomplete-0.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:18:50]]></Time>
<TimeTick>1643728730</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="279" >
<Disp><![CDATA[mat-autocomplete-0.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Submit.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:19:24]]></Time>
<TimeTick>1643728764</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="517" >
<Disp><![CDATA[Submit.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[WebEdit.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:19:54]]></Time>
<TimeTick>1643728794</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="729" >
<Disp><![CDATA[WebEdit.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="278" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="277" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Enter user name]]></Obj>
<Details ><![CDATA[User Name filed does not exist ]]></Details>
<Time><![CDATA[2/1/2022 - 15:19:54]]></Time>
<TimeTick>1643728794</TimeTick>
<NodeArgs eType="User" icon="10" nRep="730" status="Failed" >
<Disp><![CDATA[Enter user name]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:20:25]]></Time>
<TimeTick>1643728825</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:20:25]]></Time>
<TimeTick>1643728825</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[WebEdit_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:20:25]]></Time>
<TimeTick>1643728825</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="874" >
<Disp><![CDATA[WebEdit_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="873" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="872" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA[Enter password]]></Obj>
<Details ><![CDATA[Password filed does not exist ]]></Details>
<Time><![CDATA[2/1/2022 - 15:20:25]]></Time>
<TimeTick>1643728825</TimeTick>
<NodeArgs eType="User" icon="10" nRep="875" status="Failed" >
<Disp><![CDATA[Enter password]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:20:55]]></Time>
<TimeTick>1643728855</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:20:55]]></Time>
<TimeTick>1643728855</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Login.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:20:55]]></Time>
<TimeTick>1643728855</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="1019" >
<Disp><![CDATA[Login.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="1018" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="1017" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:21:27]]></Time>
<TimeTick>1643728887</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:21:27]]></Time>
<TimeTick>1643728887</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Just log me in.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:21:27]]></Time>
<TimeTick>1643728887</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="1163" >
<Disp><![CDATA[Just log me in.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="1162" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="1161" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Evolution]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:21:58]]></Time>
<TimeTick>1643728918</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:21:58]]></Time>
<TimeTick>1643728918</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Click here to re-try loading.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:21:58]]></Time>
<TimeTick>1643728918</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="1307" >
<Disp><![CDATA[Click here to re-try loading.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="1306" >
<Disp><![CDATA[Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="1305" >
<Disp><![CDATA[Evolution]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj ><![CDATA[Evolution home Page should display]]></Obj>
<Details ><![CDATA[Evolution home Page is not displayed]]></Details>
<Time><![CDATA[2/1/2022 - 15:21:58]]></Time>
<TimeTick>1643728918</TimeTick>
<NodeArgs eType="User" icon="10" nRep="1308" status="Failed" >
<Disp><![CDATA[Evolution home Page should display]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:22:30]]></Time>
<TimeTick>1643728950</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:22:30]]></Time>
<TimeTick>1643728950</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[NC_QuickLink.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/1/2022 - 15:22:30]]></Time>
<TimeTick>1643728950</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="1452" >
<Disp><![CDATA[NC_QuickLink.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="1451" >
<Disp><![CDATA[Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="1450" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[Click on QuickLinks]]></Obj>
<Details ><![CDATA[Clicked on Quick Links]]></Details>
<Time><![CDATA[2/1/2022 - 15:22:30]]></Time>
<TimeTick>1643728950</TimeTick>
<NodeArgs eType="User" icon="10" nRep="1453" status="Failed" >
<Disp><![CDATA[Click on QuickLinks]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:22:52]]></Time>
<TimeTick>1643728972</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/1/2022 - 15:22:52]]></Time>
<TimeTick>1643728972</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Sales]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"Sales"&nbsp;object's&nbsp;parent&nbsp;"Browser"&nbsp;(class&nbsp;Browser).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[2/1/2022 - 15:22:52]]></Time>
<TimeTick>1643728972</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>miccommentproperty = <br>Mercury Class = Browser<br>CreationTime = 0<br>|Title = https://evolution-dev.uk.pri.o2.com/O2NRFE/Controller.jpf<br>openurl = https://evolution-dev.uk.pri.o2.com/O2NRFE<br>opentitle = <br>Opened By Testing Tool = 0<br>number of tabs = 1<br>Name = <br>Has Toolbar = 0<br>Has Status Bar = 0<br>Has Menu Bar = -1<br>]]></Details>
<Time><![CDATA[2/1/2022 - 15:22:52]]></Time>
<TimeTick>1643728972</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="1598" status="Warning" nType="Parent description" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="15" nRep="1597" status="Failed" nType="Run Error" >
<Disp><![CDATA[Sales]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="1596" status="Failed" >
<Disp><![CDATA[Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="1595" status="Failed" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[2/1/2022 - 15:22:52]]></Time>
<TimeTick>1643728972</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;Sales&quot; object's parent &quot;Browser&quot; (class Browser).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: C:\OnStack_InStoreSales\Automation\FunctionLibrary\CommonFunctions.qfl<BR/>Line (405): &quot;	Browser(&quot;Browser&quot;).Page(&quot;Page&quot;).Link(&quot;Sales&quot;).HoverTap&quot;.]]></Details>
<Time><![CDATA[2/1/2022 - 15:22:52]]></Time>
<TimeTick>1643728972</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="1600" status="Failed" Source="C:\OnStack_InStoreSales\Automation\FunctionLibrary\CommonFunctions.qfl" SourceLine="404" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2/1/2022 - 15:23:00]]></Time>
<TimeTick>1643728980</TimeTick>
<NodeArgs eType="General" icon="17" nRep="1601" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="1599" status="Failed" Source="C:\OnStack_InStoreSales\Automation\FunctionLibrary\CommonFunctions.qfl" SourceLine="-1" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2/1/2022 - 15:17:49" eTime="2/1/2022 - 15:23:00" passed="5" failed="6" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[TC_75 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2/1/2022 - 15:17:48" eTime="2/1/2022 - 15:23:00" passed="5" failed="6" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test TC_75 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>