<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2E2E919R2"><DocLocation><![CDATA[C:\OnStack_InStoreSales\Automation\TestScripts\AO2_01_ISS_UAT_135_SIMO Order]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[AO2_01_ISS_UAT_135_SIMO Order]]></DName>
<Res><![CDATA[Res10]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:30]]></Time>
<TimeTick>1620705090</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="8" status="Passed" Source="Action1" SourceLine="47" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:32]]></Time>
<TimeTick>1620705092</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Till.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:32]]></Time>
<TimeTick>1620705092</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="11" >
<Disp><![CDATA[Till.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Login.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:32]]></Time>
<TimeTick>1620705092</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="13" >
<Disp><![CDATA[Login.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:32]]></Time>
<TimeTick>1620705092</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="15" >
<Disp><![CDATA[Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Login.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1234"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:32]]></Time>
<TimeTick>1620705092</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" >
<Disp><![CDATA[Login.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:32]]></Time>
<TimeTick>1620705092</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" >
<Disp><![CDATA[Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Override.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:32]]></Time>
<TimeTick>1620705092</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" >
<Disp><![CDATA[Override.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Override.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:32]]></Time>
<TimeTick>1620705092</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="22" >
<Disp><![CDATA[Override.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Get Orders.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:36]]></Time>
<TimeTick>1620705096</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="23" Source="Action1" SourceLine="53" >
<Disp><![CDATA[Get Orders.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Get Orders.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:36]]></Time>
<TimeTick>1620705096</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="25" Source="Action1" SourceLine="54" >
<Disp><![CDATA[Get Orders.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Pending Orders.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:38]]></Time>
<TimeTick>1620705098</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="26" Source="Action1" SourceLine="58" >
<Disp><![CDATA[Pending Orders.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Pending Orders.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:38]]></Time>
<TimeTick>1620705098</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="28" Source="Action1" SourceLine="59" >
<Disp><![CDATA[Pending Orders.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Pending Orders.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:43]]></Time>
<TimeTick>1620705103</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="30" Source="Action1" SourceLine="63" >
<Disp><![CDATA[Pending Orders.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Retrieve Order Details.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:45]]></Time>
<TimeTick>1620705105</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="31" Source="Action1" SourceLine="68" >
<Disp><![CDATA[Retrieve Order Details.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Retrieve Order Details.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:45]]></Time>
<TimeTick>1620705105</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="33" Source="Action1" SourceLine="69" >
<Disp><![CDATA[Retrieve Order Details.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Complete Transaction.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:47]]></Time>
<TimeTick>1620705107</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="34" Source="Action1" SourceLine="72" >
<Disp><![CDATA[Complete Transaction.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Complete Transaction.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:47]]></Time>
<TimeTick>1620705107</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="36" Source="Action1" SourceLine="73" >
<Disp><![CDATA[Complete Transaction.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[icon-checkbox.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:49]]></Time>
<TimeTick>1620705109</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="37" Source="Action1" SourceLine="81" >
<Disp><![CDATA[icon-checkbox.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[icon-checkbox.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:49]]></Time>
<TimeTick>1620705109</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="39" Source="Action1" SourceLine="82" >
<Disp><![CDATA[icon-checkbox.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Confirm.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:51]]></Time>
<TimeTick>1620705111</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="40" Source="Action1" SourceLine="86" >
<Disp><![CDATA[Confirm.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:51]]></Time>
<TimeTick>1620705111</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="42" Source="Action1" SourceLine="87" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Confirm.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:51]]></Time>
<TimeTick>1620705111</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="43" Source="Action1" SourceLine="90" >
<Disp><![CDATA[Confirm.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="10" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[SIMO Order - Transaction Completed]]></Obj>
<Details ><![CDATA[Test Passed]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:51]]></Time>
<TimeTick>1620705111</TimeTick>
<NodeArgs eType="User" icon="10" nRep="44" status="Passed" Source="Action1" SourceLine="91" >
<Disp><![CDATA[SIMO Order - Transaction Completed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:56]]></Time>
<TimeTick>1620705116</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[OK.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/11/2021 - 4:51:56]]></Time>
<TimeTick>1620705116</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="47" Source="Action1" SourceLine="98" >
<Disp><![CDATA[OK.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].GetROProperty "text"]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:18]]></Time>
<TimeTick>1620705138</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="50" status="Warning" Source="Action1" SourceLine="102" >
<Disp><![CDATA[[ JavaStaticText ].GetROProperty "text"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"[&nbsp;JavaStaticText&nbsp;]"&nbsp;(of&nbsp;class&nbsp;JavaStaticText).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:18]]></Time>
<TimeTick>1620705138</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>to_class = JavaStaticText<br>Text = £.*<br>]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:18]]></Time>
<TimeTick>1620705138</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="52" status="Warning" nType="Description" Source="Action1" SourceLine="102" >
<Disp><![CDATA[[ JavaStaticText ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="51" status="Failed" nType="Run Error" Source="Action1" SourceLine="102" >
<Disp><![CDATA[[ JavaStaticText ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Enter.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:22]]></Time>
<TimeTick>1620705142</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="53" Source="Action1" SourceLine="110" >
<Disp><![CDATA[Enter.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Enter.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:23]]></Time>
<TimeTick>1620705143</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="55" Source="Action1" SourceLine="111" >
<Disp><![CDATA[Enter.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Enter]]></Obj>
<Details plainTxt="False" ><![CDATA[The&nbsp;operation&nbsp;cannot&nbsp;be&nbsp;performed]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:23]]></Time>
<TimeTick>1620705143</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Enter]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>to_class = JavaButton<br>Label = Enter<br>]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:23]]></Time>
<TimeTick>1620705143</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="57" status="Warning" nType="Description" Source="Action1" SourceLine="111" >
<Disp><![CDATA[Enter]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="56" status="Failed" nType="Run Error" Source="Action1" SourceLine="111" >
<Disp><![CDATA[Enter]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:28]]></Time>
<TimeTick>1620705148</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="59" Source="Action1" SourceLine="115" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:33]]></Time>
<TimeTick>1620705153</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="61" Source="Action1" SourceLine="126" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="46" status="Failed" Source="Action1" SourceLine="98" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:35]]></Time>
<TimeTick>1620705155</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Save Print Output As]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:35]]></Time>
<TimeTick>1620705155</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Cancel.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:35]]></Time>
<TimeTick>1620705155</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="67" Source="Action1" SourceLine="131" >
<Disp><![CDATA[Cancel.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Cancel.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:37]]></Time>
<TimeTick>1620705157</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="71" Source="Action1" SourceLine="136" >
<Disp><![CDATA[Cancel.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Cancel.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:39]]></Time>
<TimeTick>1620705159</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="75" Source="Action1" SourceLine="140" >
<Disp><![CDATA[Cancel.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:43]]></Time>
<TimeTick>1620705163</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="77" Source="Action1" SourceLine="148" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[5/11/2021 - 4:52:43]]></Time>
<TimeTick>1620705163</TimeTick>
<NodeArgs eType="General" icon="16" nRep="78" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="14" nRep="66" Source="Action1" SourceLine="131" >
<Disp><![CDATA[Save Print Output As]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="65" Source="Action1" SourceLine="131" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/11/2021 - 4:51:26" eTime="5/11/2021 - 4:52:43" passed="2" failed="2" warnings="3" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[AO2_01_ISS_UAT_135_SIMO Order Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="5/11/2021 - 4:51:24" eTime="5/11/2021 - 4:52:43" passed="2" failed="2" warnings="3" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test AO2_01_ISS_UAT_135_SIMO Order Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>